# This file defines how the builder image is built. The file expects
# the following substitutions:
#   _DOCKER_NAMESPACE, the repository where to push the images.
#   _TAG, the tag to use for the published images.
steps:
# Build the builder image.
- name: gcr.io/cloud-builders/docker
  args: [ 'build', '-t', '${_DOCKER_NAMESPACE}/aspnetcorebuild:${_TAG}',
          '--no-cache', '--pull', './src' ]
  id: 'builder-build'

# Test the images structure.
- name: gcr.io/gcp-runtimes/structure_test
  args: ['-i', '${_DOCKER_NAMESPACE}/aspnetcorebuild:${_TAG}',
         '--config', '/workspace/structural_tests/aspnet.yaml', '-v']
  id: 'builder-test'

# Publish the images.
images:
  - '${_DOCKER_NAMESPACE}/aspnetcorebuild:${_TAG}'
